options:
  driver-source:
    type: string
    default:
    description: |
      Optional configuration to support use of additional sources such as:
        - ppa:myteam/ppa
        - cloud:trusty-proposed/kilo
        - http://my.archive.com/ubuntu main
      The last option should be used in conjunction with the key configuration
      option.
  driver-key:
    type: string
    default:
    description: |
      Key ID to import to the apt keyring to support use with arbitary source
      configuration from outside of Launchpad archives or PPA's.
